version: '3.8'


networks:
  freeport:
    external: true
services:
  xmrwallet:
    container_name: freeport-xmr
    image: freeport/freeport-xmr
    restart: on-failure
    build:
        context: ./
        dockerfile: ./Dockerfile
    volumes:
        - ./:/app
        - freeport_wallet_xmr:/home/droid/freeport/data
    ports:
      - '5085:5085'
    networks:
      - freeport
volumes:

  freeport_wallet_xmr:
  db:
    driver: local
